services:
  api:
    image: crpi-v3f25e0qtnv1cbc5.cn-shanghai.personal.cr.aliyuncs.com/jac0b_shi/ultrafast_laser_process_decision_agent:api-latest
    container_name: ultrafast-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments

  web:
    image: crpi-v3f25e0qtnv1cbc5.cn-shanghai.personal.cr.aliyuncs.com/jac0b_shi/ultrafast_laser_process_decision_agent:web-latest
    container_name: ultrafast-web
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:3000"