"use client";
import Link from "next/link";
import {useState} from "react";
import {Avatar} from "@/components/account-panel";
type User={username:string;admin:boolean;avatar_url?:string|null};
type History={id:string;title?:string};
export default function AuthenticatedSidebar({user,busy,page,history,onNewTask,onOpen,onOpenHistory,onLogout}:{user:User;busy:boolean;page:string;history:History[];onNewTask:()=>void;onOpen:(page:string)=>void;onOpenHistory:(id:string)=>void;onLogout:()=>void}){
 const [menuOpen,setMenuOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false);
 const primary=[["chat","对话推荐"],["analysis","工艺分析"],["data","我的加工反馈"],["knowledge","知识文件"]];
 const account=[["wallet","余额与消费"],["profile","个人资料"],["trash","回收站"],...(user.admin?[["admin","管理中心"]]:[])];
 const choose=(next:string)=>{setAccountOpen(false);onOpen(next);};
 return <aside className="relative flex flex-col gap-3 border-r bg-[#f0f1ec] p-5 md:fixed md:inset-y-0 md:w-64"><p className="pt-5 text-xs tracking-widest text-teal-800">LASER / AI</p><h1 className="mb-5 text-lg font-semibold">超快激光加工工艺数据库智能体系统</h1><button disabled={busy} className="rounded-xl border bg-white p-3 text-left" onClick={onNewTask}>＋ 新的加工任务</button><button className="text-left text-sm md:hidden" onClick={()=>setMenuOpen(!menuOpen)}>菜单 {menuOpen?"收起":"展开"}</button><div className={`${menuOpen?"flex":"hidden md:flex"} min-h-0 flex-1 flex-col gap-2`}><nav className="flex flex-col gap-1">{primary.map(([key,label])=><button key={key} disabled={busy} className={`rounded-lg p-2 text-left ${page===key?"bg-stone-200":""}`} onClick={()=>choose(key)}>{label}</button>)}</nav><Link href="/legacy" className="mt-1 rounded-lg border border-stone-300 px-3 py-2 text-xs text-stone-600 hover:bg-white hover:text-teal-800">旧版参数推荐（免登录） →</Link><section className="mt-4 min-h-0 flex-1 overflow-y-auto"><p className="sticky top-0 bg-[#f0f1ec] pb-2 text-xs text-stone-500">最近任务</p><div className="space-y-1">{history.slice().reverse().map(item=><button key={item.id} disabled={busy} className="block w-full truncate rounded-lg p-2 text-left text-sm hover:bg-stone-200" onClick={()=>onOpenHistory(item.id)}>{item.title}</button>)}</div>{!history.length&&<p className="p-2 text-xs text-stone-400">还没有任务</p>}</section><div className="relative mt-auto border-t border-stone-300 pt-3">{accountOpen&&<div role="menu" className="absolute bottom-14 left-0 right-0 z-20 rounded-xl border bg-white p-2 shadow-xl">{account.map(([key,label])=><button key={key} disabled={busy} className={`block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-stone-100 ${page===key?"text-teal-800":""}`} onClick={()=>choose(key)}>{label}</button>)}<div className="my-1 border-t"/><button disabled={busy} className="block w-full rounded-lg px-3 py-2 text-left text-sm text-red-700 hover:bg-red-50" onClick={()=>{setAccountOpen(false);onLogout();}}>退出登录</button></div>}<button aria-expanded={accountOpen} aria-haspopup="menu" className="flex w-full items-center gap-2 rounded-xl p-2 text-left hover:bg-white" onClick={()=>setAccountOpen(!accountOpen)}><Avatar url={user.avatar_url} name={user.username}/><span className="min-w-0 flex-1 truncate text-sm font-medium">{user.username}</span><span className="text-stone-400">{accountOpen?"⌄":"⌃"}</span></button></div></div></aside>;
}
