"use client";
import Link from "next/link";
import {useState} from "react";
import {apiFetch} from "@/lib/api";

type User={id:string;username:string;admin:boolean;email?:string|null;avatar_url?:string|null};
const input="border rounded-xl p-3 w-full bg-white";
const button="rounded-xl bg-teal-800 text-white px-5 py-3 disabled:opacity-40";
const post=(body:unknown)=>({method:"POST",body:JSON.stringify(body)});

export default function AuthScreen({onLogin}:{onLogin:(user:User)=>void}){
 const [mode,setMode]=useState<"login"|"register">("login"),[username,setUsername]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function submit(){setBusy(true);setError("");setNotice("");try{if(mode==="login"){onLogin(await apiFetch<User>("/api/agent/login",post({username,password})));}else{if(password!==confirm)throw new Error("两次输入的密码不一致");const result=await apiFetch<{message:string}>("/api/agent/register",post({username,email,password}));setNotice(result.message);setPassword("");setConfirm("");}}catch(e){setError(e instanceof Error?e.message:"操作失败");}finally{setBusy(false);}}
 return <main className="min-h-screen flex items-center justify-center bg-stone-50 p-6"><div className="w-full max-w-md space-y-4"><form className="bg-white border rounded-3xl p-8 md:p-10 space-y-5" onSubmit={e=>{e.preventDefault();void submit();}}><p className="text-xs tracking-widest text-teal-800">LASER RESEARCH ASSISTANT</p><h1 className="text-2xl font-semibold">{mode==="login"?"登录超快激光加工工艺数据库智能体":"注册研究账号"}</h1><p className="text-sm text-stone-500">{mode==="login"?"登录后，个人反馈与文件按账号隔离。":"验证邮箱后账号才会创建；初始余额与信用额度均为零。"}</p><label className="block">用户名<input className={input} autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label>{mode==="register"&&<label className="block">邮箱<input className={input} type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>}<label className="block">密码<input className={input} type="password" minLength={mode==="register"?12:undefined} autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{mode==="register"&&<label className="block">确认密码<input className={input} type="password" minLength={12} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>}{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-teal-50 p-3 text-teal-900">{notice}</p>}<button className={button+" w-full"} disabled={busy}>{busy?"处理中…":mode==="login"?"登录":"发送验证邮件"}</button><button type="button" className="w-full text-sm text-teal-800" onClick={()=>{setMode(mode==="login"?"register":"login");setError("");setNotice("");}}>{mode==="login"?"没有账号？邮箱注册":"已有账号？返回登录"}</button></form><Link className="block rounded-2xl border bg-white px-5 py-4 text-center text-sm text-teal-800 hover:bg-teal-50" href="/legacy">免登录体验旧版参数推荐，用于效果对比 →</Link></div></main>;
}
