"use client";
import {KeyboardEvent,useEffect,useRef,useState} from "react";
import ImageAttachments,{ChatImage} from "@/components/image-attachments";
import AgentResultDetails from "@/components/agent-result-details";
import {DeviceConstraints} from "@/components/agent-fields";
import {metricLabel} from "@/lib/metric-display";
import {apiFetch} from "@/lib/api";
type Material={name:string;metrics:string[]}; type Model={id:string;name:string;default:boolean;supports_images:boolean;sale:Record<string,string>};
type Result={id:string;source:string;parameters:Record<string,number>;quality:Record<string,number>;match_score:number;similar_cases:{case_id:string}[];provider:{message:string};task:Task;model_versions?:Record<string,string>};
type ToolEvent={tool:string;status?:"running"|"done"|"failed";summary:string;data?:Record<string,unknown>};
type Task={material?:string;targets?:Record<string,{value?:number;tolerance?:number;operator?:string;unit?:string}>;algorithm?:string;constraints?:Record<string,unknown>};
type Turn={role?:string;text:string;assistant?:string;events?:ToolEvent[];task?:Task;recommendation?:Result;recommendation_id?:string;result?:Result;pending?:boolean;failed?:boolean;context_truncated?:boolean};
const field="mt-1 w-full rounded-lg border bg-white p-2 text-sm";
const examples=["飞秒和皮秒激光的加工机理有什么差异？","数据集里有哪些材料？","为 CFRP 加工深度 15 μm、容差 1 μm 推荐参数"];

export default function ConversationPanel({materials,models,conversation,onConversation,initial,onRefresh,busy,setBusy,setError}:{materials:Material[];models:Model[];conversation:string;onConversation:(id:string)=>void;initial:Turn[];onRefresh:()=>Promise<void>;busy:boolean;setBusy:(value:boolean)=>void;setError:(value:string)=>void}){
 const [turns,setTurns]=useState<Turn[]>(initial),[message,setMessage]=useState(""),[images,setImages]=useState<ChatImage[]>([]),[modelId,setModelId]=useState(""),[task,setTask]=useState<Task>({targets:{},algorithm:"auto",constraints:{}}),[composing,setComposing]=useState(false),[following,setFollowing]=useState(true);
 const end=useRef<HTMLDivElement>(null),abortRef=useRef<AbortController|null>(null),requestRef=useRef<{id:string;key:string}|null>(null);
 const active=modelId==="local"?undefined:models.find(model=>modelId?model.id===modelId:model.default);
 useEffect(()=>{const safe=Array.isArray(initial)?initial.filter((t):t is Turn=>Boolean(t&&typeof t==="object")):[];setTurns(safe);const last=[...safe].reverse().find(t=>t.task&&typeof t.task==="object");if(last?.task)setTask(last.task);},[initial]);
 useEffect(()=>{if(!active?.supports_images)setImages([]);},[active?.supports_images]);
 useEffect(()=>{if(following){end.current?.scrollIntoView({block:"end"});}},[turns,busy,following]);
 useEffect(()=>{const watch=()=>setFollowing(document.documentElement.scrollHeight-window.scrollY-window.innerHeight<180);window.addEventListener("scroll",watch,{passive:true});return()=>window.removeEventListener("scroll",watch);},[]);
 function updateTarget(key:string,update:Record<string,unknown>){setTask(old=>({...old,targets:{...(old.targets??{}),[key]:{...(old.targets??{})[key],...update,unit:"um",operator:"eq"}}}));}
 function primary(){return Object.keys(task.targets??{})[0]??"depth_um";}
 function updatePending(change:(turn:Turn)=>Turn){setTurns(old=>old.map((turn,index)=>index===old.length-1&&turn.pending?change(turn):turn));}
 async function send(forceRecommendation=false,retryText?:string){
  if(busy)return;const draft=retryText??message;if(!draft.trim()&&!images.length&&!forceRecommendation)return;
  setBusy(true);setError("");setFollowing(true);let id=conversation;const text=forceRecommendation?(draft.trim()||"请根据当前目标推荐一组加工参数"):draft;
  try{
   if(!id){id=(await apiFetch<{id:string}>("/api/agent/conversations",{method:"POST",body:"{}"})).id;onConversation(id);}
   const key=crypto.randomUUID(),controller=new AbortController();abortRef.current=controller;requestRef.current={id,key};setTurns(old=>[...old,{role:"user",text,assistant:"",events:[],pending:true}]);
   const response=await fetch(`/api/agent/conversations/${id}/turns/stream`,{method:"POST",headers:{"Content-Type":"application/json","Accept":"text/event-stream"},body:JSON.stringify({message:text,target_update:task,model_id:modelId||null,images,request_key:key}),signal:controller.signal});
   if(!response.ok)throw new Error((await response.json()).detail??`HTTP ${response.status}`);if(!response.body)throw new Error("浏览器不支持流式响应");
   const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",finalTask:Task|undefined,recommendation:Result|undefined,done=false;
   const handle=(kind:string,data:any)=>{if(kind==="answer")updatePending(t=>({...t,assistant:(t.assistant??"")+String(data.text??"")}));if(kind==="tool")updatePending(t=>{const events=[...(t.events??[])],running=events.findLastIndex(e=>e.tool===data.tool&&e.status==="running");if(data.status!=="running"&&running>=0)events[running]=data;else events.push(data);return {...t,events};});if(kind==="result"){finalTask=data.task;recommendation=data.recommendation;updatePending(t=>({...t,task:data.task,recommendation:data.recommendation,context_truncated:data.context_truncated}));}if(kind==="done"){done=true;updatePending(t=>({...t,pending:false}));}if(kind==="stopped")updatePending(t=>({...t,pending:false,failed:true,assistant:t.assistant||data.message}));if(kind==="error")throw new Error(data.message||"对话处理失败");};
   while(true){const part=await reader.read();if(part.done)break;buffer+=decoder.decode(part.value,{stream:true});let boundary;while((boundary=buffer.indexOf("\n\n"))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);if(block.startsWith(":"))continue;const kind=block.match(/^event: (.+)$/m)?.[1],raw=block.match(/^data: (.+)$/m)?.[1];if(kind&&raw)handle(kind,JSON.parse(raw));}}
   if(!done)throw new Error("连接在完成前中断，可点击重试");if(finalTask)setTask(finalTask);if(recommendation)updatePending(t=>({...t,recommendation}));setMessage("");setImages([]);await onRefresh();
  }catch(error){if((error as Error).name!=="AbortError"){const textError=error instanceof Error?error.message:"发送失败，草稿已保留。";setError(textError);updatePending(t=>({...t,pending:false,failed:true,assistant:t.assistant||textError}));}}finally{abortRef.current=null;requestRef.current=null;setBusy(false);}
 }
 async function stop(){const current=requestRef.current;try{if(current)await apiFetch(`/api/agent/conversations/${current.id}/turns/${current.key}/cancel`,{method:"POST",body:"{}"});}finally{updatePending(t=>({...t,pending:false,failed:true,assistant:t.assistant||"已停止生成"}));abortRef.current?.abort();}}
 function keydown(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==="Enter"&&!event.shiftKey&&!composing&&!event.nativeEvent.isComposing){event.preventDefault();void send();}}
 const selected=primary(),target=(task.targets??{})[selected]??{};
 return <section className="flex min-h-[calc(100vh-7rem)] flex-col"><header className="py-7"><p className="text-sm text-teal-800">超快激光加工工艺数据库智能体系统</p><h2 className="mt-2 text-3xl font-semibold">今天，想先讨论什么？</h2><p className="mt-3 text-stone-500">可以提问、补充加工目标或上传图片；需要数值参数时，我会调用案例与推荐工具。</p></header>
 <div className="flex-1 space-y-5 pb-52">{!turns.length&&<div className="rounded-2xl border bg-white p-6"><p className="text-stone-600">试试这些问题：</p><div className="mt-3 flex flex-wrap gap-2">{examples.map(item=><button key={item} className="rounded-full border px-4 py-2 text-sm text-teal-800 hover:bg-teal-50" onClick={()=>setMessage(item)}>{item}</button>)}</div></div>}{turns.map((turn,index)=><article key={index} className="space-y-3"><div className="ml-auto max-w-3xl rounded-2xl bg-teal-800 px-5 py-3 text-white whitespace-pre-wrap">{typeof turn.text==="string"?turn.text:"（历史消息）"}</div>{typeof turn.assistant==="string"&&turn.assistant&&<div className="max-w-3xl rounded-2xl border bg-white p-5 whitespace-pre-wrap">{turn.assistant}{turn.pending&&<span className="ml-1 inline-block h-4 w-1 animate-pulse bg-teal-700 align-middle"/>}</div>}{Array.isArray(turn.events)&&turn.events.length?<details open={turn.pending} className="max-w-3xl rounded-xl border bg-stone-50 p-3 text-sm"><summary className="cursor-pointer text-teal-800">执行过程</summary><div className="mt-3 space-y-2">{turn.events.map((event,i)=><div key={i} className="flex gap-2"><span>{event.status==="running"?"◌":event.status==="failed"?"×":"✓"}</span><span><b>{event.tool}</b>：{event.summary}</span></div>)}</div></details>:null}{turn.context_truncated&&<p className="text-xs text-amber-700">本轮仅使用最近 12 组历史消息和当前结构化目标。</p>}{turn.recommendation&&<Recommendation result={turn.recommendation}/>} {turn.failed&&!turn.pending&&<button className="text-sm text-teal-800" disabled={busy} onClick={()=>void send(false,turn.text)}>重试本轮</button>}</article>)}</div>
 {!following&&<button className="fixed bottom-44 right-6 z-20 rounded-full border bg-white px-4 py-2 text-sm shadow" onClick={()=>{setFollowing(true);end.current?.scrollIntoView({block:"end"});}}>回到最新</button>}
 <div className="sticky bottom-3 z-10 rounded-2xl border bg-white p-4 shadow-lg"><details className="mb-3"><summary className="cursor-pointer text-sm text-teal-800">加工目标（可编辑）</summary><div className="mt-3 grid gap-3 md:grid-cols-5"><label className="text-xs">材料<select className={field} value={task.material??""} onChange={e=>setTask(old=>({...old,material:e.target.value,targets:{}}))}><option value="">选择材料</option>{materials.map(m=><option key={m.name}>{m.name}</option>)}</select></label><label className="text-xs">指标<select className={field} value={selected} onChange={e=>updateTarget(e.target.value,{})}>{(materials.find(m=>m.name===task.material)?.metrics??["depth_um"]).map(key=><option key={key} value={key}>{metricLabel(key)}</option>)}</select></label><label className="text-xs">目标 / μm<input className={field} type="number" min="0" value={target.value??""} onChange={e=>updateTarget(selected,{value:Number(e.target.value)})}/></label><label className="text-xs">容差 / μm<input className={field} type="number" min="0" value={target.tolerance??""} onChange={e=>updateTarget(selected,{tolerance:Number(e.target.value)})}/></label><label className="text-xs">算法<select className={field} value={task.algorithm??"auto"} onChange={e=>setTask(old=>({...old,algorithm:e.target.value}))}><option value="auto">自动选择</option></select></label></div><details className="mt-3"><summary className="text-sm text-stone-500">设备约束</summary><DeviceConstraints value={JSON.stringify(task.constraints??{})} onChange={value=>setTask(old=>({...old,constraints:JSON.parse(value)}))}/></details></details>
 <div className="flex items-end gap-3"><div className="flex-1"><textarea aria-label="对话输入" className="min-h-20 w-full resize-none outline-none" placeholder="输入问题或加工需求…（Enter 发送，Shift+Enter 换行）" value={message} onChange={e=>setMessage(e.target.value)} onCompositionStart={()=>setComposing(true)} onCompositionEnd={()=>setComposing(false)} onKeyDown={keydown}/><div className="mt-2 flex flex-wrap items-center gap-3"><select aria-label="AI 模型" className="rounded-lg border p-2 text-sm" value={modelId} onChange={e=>setModelId(e.target.value)}><option value="">默认 · {active?.name??"管理员默认模型"}</option><option value="local">免费 · 本地确定性模式</option>{models.filter(model=>!model.default).map(model=><option key={model.id} value={model.id}>{model.name}</option>)}</select>{active?.supports_images&&<ImageAttachments enabled value={images} onChange={setImages} onError={setError}/>} {active&&<details className="text-xs text-stone-500"><summary>模型费用说明</summary>输入 {active.sale?.uncached??"—"}／百万 token，输出 {active.sale?.output??"—"}／百万 token</details>}</div></div><div className="flex flex-col gap-2"><button className="rounded-xl border px-4 py-2 text-sm text-teal-800" disabled={busy} onClick={()=>void send(true)}>生成参数</button>{busy?<button className="rounded-xl bg-stone-700 px-5 py-3 text-white" onClick={()=>void stop()}>停止</button>:<button className="rounded-xl bg-teal-800 px-5 py-3 text-white disabled:opacity-40" disabled={!message.trim()&&!images.length} onClick={()=>void send()}>发送</button>}</div></div></div><div ref={end}/></section>;
}
function Recommendation({result}:{result:Result}){const [actual,setActual]=useState<Record<string,string>>({}),[saved,setSaved]=useState(false),[error,setError]=useState("");async function save(){setError("");try{const quality=Object.fromEntries(Object.entries(actual).filter(([,v])=>v!=="").map(([k,v])=>[k,Number(v)]));if(!Object.keys(quality).length)throw new Error("请填写至少一个实测质量值");await apiFetch("/api/agent/feedback",{method:"POST",body:JSON.stringify({recommendation_id:result.id,quality})});setSaved(true);}catch(e){setError(e instanceof Error?e.message:"保存失败");}}return <article className="max-w-3xl space-y-4 rounded-2xl border bg-white p-5"><h3 className="font-semibold">{result.source==="historical"?"历史案例参数":"推荐参数"}<span className="float-right text-sm text-teal-800">匹配 {(result.match_score*100).toFixed(1)}%</span></h3><dl className="grid grid-cols-2 gap-2 md:grid-cols-3">{Object.entries(result.parameters).map(([key,value])=><div key={key} className="rounded-lg bg-stone-50 p-2"><dt className="text-xs text-stone-500">{metricLabel(key)}</dt><dd>{Number(value.toPrecision(6))}</dd></div>)}</dl><p className="text-sm text-stone-500">案例依据：{result.similar_cases.length} 条同材料实测记录</p><details><summary className="cursor-pointer text-sm text-teal-800">推荐逻辑、公式、训练信息与依据</summary><AgentResultDetails result={result}/></details>{result.id&&<details><summary className="cursor-pointer text-sm text-teal-800">保存本次实测反馈</summary><div className="mt-3 flex flex-wrap items-end gap-3">{Object.keys(result.quality).map(key=><label key={key} className="text-xs">{metricLabel(key)} / μm<input className={field} type="number" min="0" value={actual[key]??""} onChange={e=>setActual(old=>({...old,[key]:e.target.value}))}/></label>)}<button className="rounded-lg bg-teal-800 px-4 py-2 text-sm text-white" disabled={saved} onClick={()=>void save()}>{saved?"已追加保存":"追加反馈"}</button></div>{error&&<p className="mt-2 text-sm text-red-700">{error}</p>}</details>}</article>}
