"use client";
import {useState} from "react";
import {apiFetch} from "@/lib/api";
import {metricLabel} from "@/lib/metric-display";
import {Measurements} from "@/components/agent-fields";
type RecordData={id:string;_revision?:number;material?:string;quality?:Record<string,number>;parameters?:Record<string,number>;deleted_at?:string};
export default function FeedbackRecord({record,trash,busy,run,refresh}:{record:RecordData;trash:boolean;busy:boolean;run:(action:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<void>}){
 const [history,setHistory]=useState<{version:number;action:string;created:string;data:RecordData}[]>([]);
 const [editing,setEditing]=useState(false),[quality,setQuality]=useState(""),[parameters,setParameters]=useState("");
 const expired=!!record.deleted_at&&Date.now()>=new Date(record.deleted_at).getTime()+30*86400000;
 return <article className="border bg-white rounded-xl p-5 mb-4"><h3>{record.material}</h3><dl className="grid grid-cols-2 gap-3 mt-3">{Object.entries(record.quality??{}).map(([k,v])=><div key={k}><dt className="text-xs text-stone-500">{metricLabel(k)}</dt><dd>{v}</dd></div>)}</dl>{editing&&<div className="mt-4 space-y-3"><p>修正实测质量</p><Measurements metrics={Object.keys(record.quality??{})} value={quality} onChange={setQuality}/><p>实际加工参数</p><Measurements metrics={Object.keys(record.parameters??{})} value={parameters} onChange={setParameters}/><button disabled={busy||!quality||!parameters} className="text-teal-800 mr-5" onClick={()=>void run(async()=>{await apiFetch(`/api/agent/feedback/${record.id}`,{method:"PUT",body:JSON.stringify({_revision:record._revision,quality:JSON.parse(quality),parameters:JSON.parse(parameters)})});setEditing(false);await refresh();})}>保存修正</button><button onClick={()=>setEditing(false)}>取消</button></div>}<div className="flex gap-5 mt-4"><button disabled={busy||expired} onClick={()=>void run(async()=>{await apiFetch(`/api/agent/feedback/${record.id}${trash?"/restore":""}`,{method:trash?"POST":"DELETE"});await refresh();})}>{trash?(expired?"已超过恢复期限":"恢复"):"移入回收站"}</button>{!trash&&!editing&&<button onClick={()=>{setQuality(JSON.stringify(record.quality));setParameters(JSON.stringify(record.parameters));setEditing(true);}}>修正实测值</button>}<button disabled={busy} onClick={()=>void run(async()=>setHistory(await apiFetch(`/api/agent/feedback/${record.id}/history`)))}>查看版本历史</button></div>{history.length>0&&<div className="border-t mt-4 pt-3 space-y-3">{history.map(h=><div key={h.version} className="text-sm"><p>{new Date(h.created).toLocaleString()} · {({create:"新增",revise:"修正",delete:"删除",restore:"恢复"} as Record<string,string>)[h.action]}</p>{Object.entries(h.data.quality??{}).map(([k,v])=><p key={k}>{metricLabel(k)}：{v}</p>)}</div>)}</div>}{record.deleted_at&&<p className="text-xs mt-3">删除于 {new Date(record.deleted_at).toLocaleString()}</p>}</article>;
}
