"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "@/lib/api";
type Formula={evidence?:{document_id:string;file:string;location:string;text:string}[];id:string;operation:string;inputs:string[];factor?:number;unit:string;source:string;status:string};
export default function FormulaReview({materials}:{materials:string[]}){
 const [items,setItems]=useState<Formula[]>([]),[material,setMaterial]=useState(materials[0]??""),[query,setQuery]=useState("pulse density repetition frequency scanning speed"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const refresh=async()=>setItems(await apiFetch<Formula[]>("/api/agent/formulas"));
 useEffect(()=>{void refresh().catch(e=>setNotice(String(e)));},[]);
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();await refresh();}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <section className="mt-10 space-y-4"><h3 className="text-xl font-semibold">知识关系与公式审核</h3><p className="text-sm text-stone-500">从公共文献提出关系，经管理员核对来源、单位与适用材料后启用。</p><select aria-label="公式适用材料" className="border rounded-lg p-2" value={material} onChange={e=>setMaterial(e.target.value)}>{materials.map(m=><option key={m}>{m}</option>)}</select><input aria-label="知识关系检索" className="border rounded-lg p-3 w-full" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy||!query.trim()} className="text-teal-800" onClick={()=>void run(async()=>{const r=await apiFetch<{message:string;id?:string}>("/api/agent/formulas/extract",{method:"POST",body:JSON.stringify({message:query,task:{material},request_key:crypto.randomUUID()})});setNotice(r.message+(r.id?" 提案已进入待审核列表。":" 请配置可用 AI 服务后提取关系。"));})}>提取关系提案</button>{notice&&<p role="status">{notice}</p>}{items.map(f=><article key={f.id} className="border rounded-xl bg-white p-4 space-y-2"><p>{f.inputs.join(f.operation==="ratio"?" ÷ ":" × ")} × {f.factor??1} [{f.unit}]</p><p className="text-sm break-all">来源：{f.source}</p><details><summary>查看文献原文</summary>{f.evidence?.map((e,i)=><div key={i} className="text-sm my-3"><a className="underline" href={`/api/agent/knowledge/${e.document_id}/download`}>{e.file} · {e.location}</a><p className="whitespace-pre-wrap">{e.text}</p></div>)}</details><p>{f.status==="approved"?"已审核启用":"待审核"}</p>{f.status==="pending"&&<button disabled={busy} className="text-teal-800" onClick={()=>void run(async()=>{await apiFetch(`/api/agent/formulas/${f.id}/approve`,{method:"POST"});setNotice("公式已审核，后续训练将采用新的公式版本。");})}>确认来源与单位并启用</button>}</article>)}</section>;
}
