"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "@/lib/api";
import {metricLabel} from "@/lib/metric-display";
type Material={name:string;metrics:string[]}; type Algorithm={id:string;name:string;category:string};
type Candidate={algorithm:string;status:string;rmse?:number;mae?:number;r2?:number;reason?:string};
type Audit={selected:string;validation_rmse:number;groups:number;samples:number;candidates:Candidate[]};
type Job={id:string;status:string;material:string;target:string;algorithms:string[];audit?:Audit;error?:string;version_id?:string};
type Version={id:string;scope:string;material:string;target:string;algorithm:string;audit:Audit;data_version:string;training_snapshot:string;feature_version:string;active:boolean;stale:boolean;created:string};
type Comparison={id:string;material:string;prediction_source?:string;predicted_quality:Record<string,number>;measured_quality:Record<string,number>;delta:Record<string,number>};
const select="rounded-lg border bg-white p-2 text-sm";
const n=(value?:number)=>typeof value==="number"&&Number.isFinite(value)?value.toFixed(4):"—";
export default function ProcessAnalysis({materials,busy,setBusy,setError}:{materials:Material[];busy:boolean;setBusy:(v:boolean)=>void;setError:(v:string)=>void}){
 const [algorithms,setAlgorithms]=useState<Algorithm[]>([]),[jobs,setJobs]=useState<Job[]>([]),[versions,setVersions]=useState<Version[]>([]),[comparisons,setComparisons]=useState<Comparison[]>([]),[material,setMaterial]=useState(""),[target,setTarget]=useState(""),[chosen,setChosen]=useState<string[]>([]);
 async function refresh(){const [a,j,v,c]=await Promise.all([apiFetch<Algorithm[]>("/api/agent/algorithms"),apiFetch<Job[]>("/api/agent/analysis/evaluations"),apiFetch<Version[]>("/api/agent/analysis/models"),apiFetch<Comparison[]>("/api/agent/analysis/feedback-comparison")]);setAlgorithms(a);setJobs(j);setVersions(v);setComparisons(c);if(!chosen.length)setChosen(a.slice(0,6).map(x=>x.id));}
 useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:"加载分析失败"));},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!jobs.some(j=>j.status==="queued"||j.status==="running"))return;const timer=setInterval(()=>void refresh(),2000);return()=>clearInterval(timer);},[jobs]);// eslint-disable-line react-hooks/exhaustive-deps
 const metrics=materials.find(m=>m.name===material)?.metrics??[];
 async function run(body:()=>Promise<unknown>){setBusy(true);setError("");try{await body();await refresh();}catch(e){setError(e instanceof Error?e.message:"操作失败");}finally{setBusy(false);}}
 return <section className="space-y-6"><header><h2 className="text-2xl font-semibold">工艺分析</h2><p className="mt-2 text-stone-500">比较同一分组划分下的开发集验证结果，管理当前账号的工艺预测模型。这里的指标不等同于独立测试成绩。</p></header>
 <article className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">发起模型评估</h3><div className="mt-4 flex flex-wrap gap-3"><select aria-label="分析材料" className={select} value={material} onChange={e=>{setMaterial(e.target.value);setTarget("");}}><option value="">选择材料</option>{materials.map(m=><option key={m.name}>{m.name}</option>)}</select><select aria-label="分析指标" className={select} value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择质量指标</option>{metrics.map(x=><option key={x} value={x}>{metricLabel(x)}</option>)}</select><button className="rounded-lg bg-teal-800 px-4 py-2 text-white disabled:opacity-40" disabled={busy||!material||!target||!chosen.length} onClick={()=>void run(()=>apiFetch("/api/agent/analysis/evaluations",{method:"POST",body:JSON.stringify({material,target,algorithms:chosen})}))}>开始评估</button></div><div className="mt-4 flex flex-wrap gap-2">{algorithms.map(a=><label key={a.id} className="rounded-full border px-3 py-1 text-sm"><input type="checkbox" className="mr-2" checked={chosen.includes(a.id)} onChange={e=>setChosen(old=>e.target.checked?[...old,a.id]:old.filter(x=>x!==a.id))}/>{a.name}</label>)}</div></article>
 <article className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">评估任务</h3>{!jobs.length&&<p className="mt-3 text-stone-500">尚未运行评估。</p>}{jobs.slice().reverse().map(job=><details key={job.id} className="mt-3 rounded-xl border p-3" open={job.status==="running"}><summary>{job.material} · {metricLabel(job.target)} · {({queued:"等待",running:"评估中",succeeded:"完成",failed:"失败"} as Record<string,string>)[job.status]??job.status}</summary>{job.error&&<p className="mt-2 text-red-700">{job.error}</p>}{job.audit&&<AuditTable audit={job.audit}/>}</details>)}</article>
 <article className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">个人模型版本</h3>{!versions.length&&<p className="mt-3 text-stone-500">评估成功后会生成不可变版本。</p>}{versions.slice().reverse().map(v=><div key={v.id} className="mt-3 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p><b>{v.material} · {metricLabel(v.target)}</b> · {v.algorithm}</p><span className={v.active?"text-teal-800":"text-stone-500"}>{v.active?"当前启用":"未启用"}{v.stale?" · 数据已有更新":""}</span></div><p className="mt-2 text-xs text-stone-500">{v.audit.samples} 条测量／{v.audit.groups} 个参数组 · RMSE {n(v.audit.validation_rmse)} · 数据快照 {v.training_snapshot.slice(0,12)}</p><div className="mt-3 flex gap-4"><button disabled={busy||v.active} className="text-teal-800 disabled:text-stone-300" onClick={()=>void run(()=>apiFetch("/api/agent/analysis/models/activate",{method:"POST",body:JSON.stringify({material:v.material,target:v.target,version_id:v.id})}))}>启用此版本</button>{v.active&&<><button disabled={busy} onClick={()=>void run(()=>apiFetch("/api/agent/analysis/models/rollback",{method:"POST",body:JSON.stringify({material:v.material,target:v.target})}))}>回滚</button><button disabled={busy} onClick={()=>void run(()=>apiFetch("/api/agent/analysis/models/activate",{method:"POST",body:JSON.stringify({material:v.material,target:v.target,version_id:null})}))}>恢复自动选模</button></>}</div></div>)}</article>
 <article className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">预测与实测反馈</h3>{!comparisons.length&&<p className="mt-3 text-stone-500">关联推荐保存反馈后，这里会显示当时预测与实测偏差；旧反馈不会事后补算。</p>}{comparisons.slice().reverse().map(c=><div key={c.id} className="mt-3 rounded-xl border p-3"><p><b>{c.material}</b> · {c.prediction_source==="case_reference"?"案例参考值":"模型预测值"}</p>{Object.keys(c.measured_quality).map(key=><p className="mt-1 text-sm" key={key}>{metricLabel(key)}：预测 {c.predicted_quality[key]??"—"}，实测 {c.measured_quality[key]}，偏差 {c.delta[key]===undefined?"—":n(c.delta[key])}</p>)}</div>)}</article></section>;
}
function AuditTable({audit}:{audit:Audit}){return <div className="mt-3 overflow-x-auto"><p className="text-sm">选中 {audit.selected}；{audit.samples} 条测量、{audit.groups} 个独立参数组。</p><table className="mt-2 min-w-[560px] w-full text-left text-xs"><thead><tr><th>算法</th><th>RMSE</th><th>MAE</th><th>R²</th><th>状态</th></tr></thead><tbody>{audit.candidates.map(c=><tr key={c.algorithm} className="border-t"><td className="py-2">{c.algorithm}</td><td>{n(c.rmse)}</td><td>{n(c.mae)}</td><td>{n(c.r2)}</td><td>{c.status}{c.reason?`：${c.reason}`:""}</td></tr>)}</tbody></table></div>}
